// lsk/resources/js/vue/default/components/Header.vue
<script setup lang="ts">
    import { getRouteUri } from '@/lib/utils';
    import { Link, useForm, usePage } from '@inertiajs/vue3';
    import ToggleAppearance from '@/vue/default/components/ToggleAppearance.vue';
    import { PageDataType } from '@/types/session';
    import LaravelSvg from '@/vue/default/icons/LaravelSvg.vue';
    import ReactSvg from '@/vue/default/icons/ReactSvg.vue';
    import VueSvg from '@/vue/default/icons/VueSvg.vue';
    import { LogIn, LogOut, User } from 'lucide-vue-next';

    const { auth } = usePage<PageDataType>().props;
    const form = useForm({});

    const handleLogout = () => {
        form.post(getRouteUri('logoutPost'));
    };
</script>

<template>
    <header class="flex flex-wrap items-center justify-center gap-4 border-b border-slate-500 py-1 pr-4 sm:justify-between sm:py-0">
        <div class="flex flex-wrap items-center justify-center">
            <a
                :href="route('livewire.home')"
                class="flex gap-1 p-2 md:px-6"
            >
                <LaravelSvg addClasses="size-7" />
                <span class="text-lg font-medium">Livewire</span>
            </a>
            <a
                :href="route('react.home')"
                class="flex gap-1 p-2 md:px-6"
            >
                <ReactSvg addClasses="size-7" />
                <span class="text-lg font-medium">React</span>
            </a>
            <Link
                :href="getRouteUri('home')"
                class="flex gap-1 p-2 md:px-6 bg-black text-white dark:bg-white dark:text-black"
            >
                <VueSvg addClasses="size-7" />
                <span class="text-lg font-medium">Vue</span>
            </Link>
        </div>

        <div class="flex flex-wrap items-center gap-2">
            <!-- auth -->
            <Link
                class="flex min-w-fit items-center gap-1 px-2 py-1"
                :href="getRouteUri('profileOverview')"
                v-if="auth?.user"
            >
                <User class="size-6" />
                <p class="font-medium">{{ auth?.user?.username }}</p>
            </Link>
            <button
                @click="handleLogout"
                type="button"
                class="flex min-w-fit items-center gap-1 rounded px-2 py-1"
                v-if="auth?.user"
            >
                <LogOut class="size-6" />
                <span class="font-medium">Logout</span>
            </button>
            <!-- endauth -->
            <!-- guest -->
            <Link
                :href="getRouteUri('login')"
                class="flex min-w-fit items-center gap-1 px-2 py-1"
                v-if="!auth?.user"
            >
                <LogIn class="size-6" />
                <p class="font-medium">Login</p>
            </Link>
            <!-- endguest -->

            <ToggleAppearance />
        </div>
    </header>
</template>

// lsk/resources/js/react/default/components/Header.tsx
import { cn, getRouteUri } from '@/lib/utils';
import ToggleAppearance from '@/react/default/components/ToggleAppearance';
import LaravelSvg from '@/react/default/icons/laravelSvg';
import ReactSvg from '@/react/default/icons/reactSvg';
import VueSvg from '@/react/default/icons/vueSvg';
import { PageDataType } from '@/types/session';
import { Link, useForm, usePage } from '@inertiajs/react';
import { LogIn, LogOut, User } from 'lucide-react';
import { useCallback } from 'react';

export default function Header() {
    const { auth } = usePage<PageDataType>().props;

    const { post } = useForm();

    const handleLogout = useCallback(() => {
        post(getRouteUri('logoutPost'));
    }, [post]);

    return (
        <header className='flex flex-wrap items-center justify-center gap-4 border-b border-slate-500 py-1 pr-4 sm:justify-between sm:py-0'>
            <div className='flex flex-wrap items-center justify-center'>
                <a
                    href={route('livewire.home')}
                    className='flex gap-1 p-2 md:px-6'
                >
                    <LaravelSvg addClasses='size-7' />
                    <span className='text-lg font-medium'>Livewire</span>
                </a>
                <Link
                    href={getRouteUri('home')}
                    className='flex gap-1 p-2 md:px-6 bg-black text-white dark:bg-white dark:text-black'
                >
                    <ReactSvg addClasses='size-7' />
                    <span className='text-lg font-medium'>React</span>
                </Link>
                <a
                    href={route('vue.home')}
                    className='flex gap-1 p-2 md:px-6'
                >
                    <VueSvg addClasses='size-7' />
                    <span className='text-lg font-medium'>Vue</span>
                </a>
            </div>

            <div className='flex flex-wrap items-center gap-2'>
                {/* auth */}
                <Link
                    href={getRouteUri('profileOverview')}
                    className={cn('flex min-w-fit items-center gap-1 px-2 py-1', {
                        hidden: !auth?.user,
                    })}
                >
                    <User className='size-6' />
                    <p className='font-medium'>{auth?.user?.username}</p>
                </Link>
                <button
                    type='button'
                    className={cn('flex min-w-fit items-center gap-1 rounded px-2 py-1', {
                        hidden: !auth?.user,
                    })}
                    onClick={handleLogout}
                >
                    <LogOut className='size-6' />
                    <span className='font-medium'>Logout</span>
                </button>
                {/* endauth */}
                {/* guest */}
                <Link
                    href={getRouteUri('login')}
                    className={cn('flex min-w-fit items-center gap-1 px-2 py-1', {
                        hidden: auth?.user,
                    })}
                >
                    <LogIn className='size-6' />
                    <p className='font-medium'>Login</p>
                </Link>
                {/* endguest */}

                <ToggleAppearance />
            </div>
        </header>
    );
}
