// lsk/resources/js/vue/default/components/ToggleAppearance.vue
<script setup lang="ts">
    import { useAppearance } from '@/vue/composables/useAppearance';
    import { Moon, Sun } from 'lucide-vue-next';

    const { appearance, updateAppearance } = useAppearance();

    const toggleAppearnece = () => {
        if (appearance.value == 'dark') {
            updateAppearance('light');
        } else {
            updateAppearance('dark');
        }
    };
</script>

<template>
    <button
        type="button"
        @click="toggleAppearnece"
        class="flex w-12 cursor-pointer items-center gap-1 rounded-full border border-black dark:border-white px-1 py-0.5"
        :class="appearance == 'light' ? 'justify-start' : 'justify-end'"
    >
        <Moon
            class="size-5 animate-in slide-in-from-left"
            v-if="appearance == 'light'"
        />
        <Sun
            class="size-5 animate-in slide-in-from-right"
            v-if="appearance != 'light'"
        />
    </button>
</template>

// lsk/resources/js/react/default/components/ToggleAppearance.tsx
import { cn } from '@/lib/utils';
import { useAppearance } from '@/react/default/hooks/use-appearance';
import { Moon, Sun } from 'lucide-react';
import { useCallback } from 'react';

export default function ToggleAppearance() {
    const { appearance, updateAppearance } = useAppearance();

    const toggleAppearnece = useCallback(() => {
        if (appearance == 'dark') {
            updateAppearance('light');
        } else {
            updateAppearance('dark');
        }
    }, [appearance, updateAppearance]);

    return (
        <button
            type='button'
            onClick={toggleAppearnece}
            className={cn('flex w-12 cursor-pointer items-center gap-1 rounded-full border px-1 py-0.5', {
                'justify-start': appearance == 'light',
                'justify-end': appearance == 'dark',
            })}
        >
            <Moon
                className={cn('animate-in slide-in-from-left size-5', {
                    hidden: appearance == 'light',
                })}
            />
            <Sun
                className={cn('animate-in slide-in-from-right size-5', {
                    hidden: appearance == 'dark',
                })}
            />
        </button>
    );
}
