// lsk/resources/js/vue/default/pages/home/IndexPage.vue
<script setup lang="ts">
    import { Head } from '@inertiajs/vue3';
    import AppLayout from '@/vue/default/layout/AppLayout.vue';
</script>

<template>
    <Head title="Vue Home"></Head>
    <AppLayout>
        <div class="flex flex-col gap-4 p-4">
            <div class="flex flex-col">
                <h2 class="text-2xl font-medium">Vue Home</h2>
            </div>
        </div>
    </AppLayout>
</template>

// lsk/resources/js/react/default/pages/home/IndexPage.tsx
import AppLayout from '@/react/default/layout/AppLayout';
import { Head } from '@inertiajs/react';

export default function Page() {
    return (
        <>
            <Head title='React Home' />
            <AppLayout>
                <div className='flex flex-col gap-4 p-4'>
                    <div className='flex flex-col'>
                        <h2 className='text-2xl font-medium'>React Home</h2>
                    </div>
                </div>
            </AppLayout>
        </>
    );
}
