// lsk/resources/js/vue/default/components/SocialLogin.vue
<script setup lang="ts">
    import { usePage } from '@inertiajs/vue3';
    import { PageDataType } from '@/types/session';
    import GoogleSvg from '@/vue/default/icons/GoogleSvg.vue';
    import GithubSvg from '@/vue/default/icons/GithubSvg.vue';

    const { errors } = usePage<PageDataType>().props;
</script>

<template>
    <div class="flex flex-col gap-2">
        <div class="flex w-full flex-wrap items-center gap-2">
            <a
                :href="route('social.google.login')"
                class="flex min-w-fit flex-1 items-center justify-center gap-1.5 rounded border px-2 py-1.5 hover:outline"
            >
                <GoogleSvg />
                <p class="font-medium tracking-tight">Continue with Google</p>
            </a>

            <a
                :href="route('social.github.login')"
                class="flex min-w-fit flex-1 items-center justify-center gap-1.5 rounded border px-2 py-1.5 hover:outline"
            >
                <GithubSvg />
                <p class="font-medium tracking-tight">Continue with Github</p>
            </a>
        </div>

        <p
            class="text-red-500"
            v-if="errors?.socialAuth"
        >
            {{ errors?.socialAuth?.[0] }}
        </p>
    </div>
</template>

// laravel-react-app/resources/js/components/general/social-login.tsx
import GithubSvg from '../svg/github-svg';
import GoogleSvg from '../svg/google-svg';
import LinkComponent from '../ui/link-component';

export default function SocialLogin() {
    return (
        <div className="flex flex-wrap items-center gap-2">
            <LinkComponent
                href={route('google.login')}
                className="flex flex-1 items-center justify-center gap-2"
            >
                <GoogleSvg />
                Google
            </LinkComponent>
            <LinkComponent
                href={route('github.login')}
                className="flex flex-1 items-center justify-center gap-2"
            >
                <GithubSvg />
                Github
            </LinkComponent>
        </div>
    );
}
