// lsk/resources/js/react/default/components/NotificationBar.tsx
import { PageDataType } from '@/types/session';
import { usePage } from '@inertiajs/react';
import { CheckCircle, Trash2 } from 'lucide-react';
import { useCallback, useEffect, useState } from 'react';

export default function NotificationBar() {
    const { session } = usePage<PageDataType>().props;

    const [title, setTitle] = useState<string>('');
    const [message, setMessage] = useState<string>('');
    const [showMessage, setShowMessage] = useState<boolean>(false);

    useEffect(() => {
        handleSession();
    }, [session?.flash]);

    const handleSession = useCallback(() => {
        switch (session?.flash) {
            case 'LOGIN_SUCCESS':
                setTitle('Login Success');
                setMessage('User Logged In Successfully');
                setShowMessage(true);
                break;

            case 'REGISTER_SUCCESS':
                setTitle('Register Success');
                setMessage('User Registered Successfully');
                setShowMessage(true);
                break;

            case 'LOGOUT_SUCCESS':
                setTitle('Logout Success');
                setMessage('User Logged Out');
                setShowMessage(true);
                break;

            case 'VERIFICATION_SUCCESS':
                setTitle('Verification Success');
                setMessage('Email Verified Successfully');
                setShowMessage(true);
                break;

            case 'PASSWORD_REQUEST':
                setTitle('Password Requested');
                setMessage('Password Request Email Sent');
                setShowMessage(true);
                break;

            case 'PASSWORD_RESET':
                setTitle('Password Reset');
                setMessage('Password Updated Succesfully');
                setShowMessage(true);
                break;

            default:
                setTitle('Success');
                setMessage('Success');
                break;
        }

        const a = setTimeout(() => {
            setShowMessage(false);
        }, 5000);
    }, [session, message]);

    return (
        <div className='fixed right-0 bottom-0 w-full'>
            <div className='flex flex-col items-end p-2'>
                <div className={`w-full max-w-80 rounded border p-2 gap-2 sm:w-80 items-center ${showMessage ? 'flex' : 'hidden'}`}>
                    <CheckCircle />

                    <div className='flex flex-1 flex-col'>
                        <p className=''>{title}</p>
                        <p className='text-xs'>{message}</p>
                    </div>

                    <button
                        onClick={() => setShowMessage(false)}
                        type='button'
                        className='flex items-center justify-center p-2 rounded'
                    >
                        <Trash2 />
                    </button>
                </div>
            </div>
        </div>
    );
}

// lsk/resources/js/vue/default/components/NotificationBar.vue
<script setup lang="ts">
    import { PageDataType } from '@/types/session';
    import { usePage } from '@inertiajs/vue3';
    import { ref, watch } from 'vue';
    const { session } = usePage<PageDataType>().props;
    import { CheckCircle, Trash2 } from 'lucide-vue-next';

    const showMessage = ref(false);
    const title = ref('');
    const message = ref('');

    const handleSession = (value?: string) => {
        switch (value) {
            case 'LOGIN_SUCCESS':
                title.value = 'Login Success';
                message.value = 'User Logged In Successfully';
                showMessage.value = true;
                break;
            case 'REGISTER_SUCCESS':
                title.value = 'Register Success';
                message.value = 'User Registered Successfully';
                showMessage.value = true;
                break;
            case 'LOGOUT_SUCCESS':
                title.value = 'Logout Success';
                message.value = 'User Logged Out';
                showMessage.value = true;
                break;
            case 'VERIFICATION_SUCCESS':
                title.value = 'Verification Success';
                message.value = 'Email Verified Successfully';
                showMessage.value = true;
                break;
            case 'PASSWORD_REQUEST':
                title.value = 'Password Requested';
                message.value = 'Password Request Email Sent';
                showMessage.value = true;
                break;
            case 'PASSWORD_RESET':
                title.value = 'Password Reset';
                message.value = 'Password Updated Successfully';
                showMessage.value = true;
                break;
            default:
                return;
        }
    };

    watch(
        () => session?.flash,
        (newValue) => {
            handleSession(newValue);
            setTimeout(() => {
                showMessage.value = false;
            }, 5000);
        },
        { immediate: true }
    );

    const toggleShowPassword = () => {
        // showMessage.value = !showMessage.value;
        showMessage.value = false;
    };
</script>

<template>
    <div class="fixed right-0 bottom-0 w-full">
        <div class="flex flex-col items-end p-2">
            <div
                class="flex w-full max-w-80 rounded border p-2 gap-2 sm:w-80 items-center"
                v-if="showMessage"
            >
                <CheckCircle />

                <div class="flex flex-1 flex-col">
                    <p class="">{{ title }}</p>
                    <p class="text-xs">{{ message }}</p>
                </div>

                <button
                    @click="toggleShowPassword"
                    type="button"
                    class="flex items-center justify-center p-2 rounded"
                >
                    <Trash2 />
                </button>
            </div>
        </div>
    </div>
</template>
